import argparse
import glob
import struct
import sys
from datetime import datetime
from pathlib import Path
from typing import List, Tuple

import numpy as np
import scipy.io as sio

# Constants
UV_PER_BIT = 0.25  # µV per A/D count for Blackrock NSPs
SPIKE_TEMPLATE_LEN_SAMPLES = 48  # 1.6 ms @ 30 kHz
DEFAULT_NEG_PEAK_UV = -100.0  # baseline spike amplitude
DEFAULT_ALPHA = 0.5  # SBP scaling factor
DEFAULT_NOISE_STD_UV = 15.0  # broadband noise SD
BIN_DURATION_S = 0.01  # 10 ms bins discovered from data (modify if probing shows otherwise)
SAMPLE_RATE = 30000  # Hz
BIN_SAMPLES = int(BIN_DURATION_S * SAMPLE_RATE)
HEADER_LABEL = b"SimData"  # <=16 bytes


def list_mat_files(glob_pattern: str) -> List[Path]:
    files = sorted(Path(f) for f in glob.glob(glob_pattern))
    if not files:
        raise FileNotFoundError(f"No .mat files found matching pattern: {glob_pattern}")
    return files


def load_mat_arrays(mat_path: Path) -> Tuple[np.ndarray, np.ndarray]:
    """Return (threshold_crossings, spike_band_power)."""
    d = sio.loadmat(mat_path)
    tc = d["binned_neural_threshold_crossings"].astype(np.int16)
    sp = d["binned_neural_spike_band_power"].astype(np.float32)
    return tc, sp


##############################
#  Spike template generation #
##############################

def build_spike_template() -> np.ndarray:
    """Return a 1-D float array of the canonical spike waveform in µV."""
    t = np.arange(SPIKE_TEMPLATE_LEN_SAMPLES) / SAMPLE_RATE
    # difference-of-exponentials negative peak + small rebound
    tau_r, tau_f = 0.00015, 0.0003  # rise/decay constants (s)
    neg = -np.exp(-t / tau_r)
    pos = 0.4 * np.exp(-t / tau_f)
    wv = neg + pos
    # normalise to −1 at min
    wv /= np.min(wv)
    return wv.astype(np.float32)


###################################
#  SBP statistics (mean / std dev) #
###################################

def compute_sbp_stats(mat_files: List[Path], n_ch: int) -> Tuple[np.ndarray, np.ndarray]:
    sum_ch = np.zeros(n_ch, dtype=np.float64)
    sumsq_ch = np.zeros(n_ch, dtype=np.float64)
    total_bins = 0
    for f in mat_files:
        _, sp = load_mat_arrays(f)
        sum_ch += sp.sum(axis=0)
        sumsq_ch += (sp ** 2).sum(axis=0)
        total_bins += sp.shape[0]
    mu = sum_ch / total_bins
    var = sumsq_ch / total_bins - mu ** 2
    sigma = np.sqrt(np.maximum(var, 1e-6))
    return mu.astype(np.float32), sigma.astype(np.float32)


################################
#  NS5 / NSx file construction #
################################

def build_basic_header(n_channels: int) -> bytes:
    """Return packed bytes for a minimal spec-2.2 NSx basic header (314 bytes)."""
    file_id = b"NEURALCD"  # 8 bytes
    file_spec = struct.pack("<BB", 2, 2)  # major, minor
    # bytes_in_header = 314 + 66*n_ch – placeholder for now (to be overwritten later)
    label = HEADER_LABEL.ljust(16, b"\x00")
    comment = f"Generated by sim_to_ns5 on {datetime.utcnow().isoformat()}".encode("ascii", errors="ignore")
    comment = comment[:255]  # ensure ≤256; leave one null terminator
    comment = comment.ljust(256, b"\x00")
    period = struct.pack("<I", 1)  # samples every TimeStampResolution / SampleResolution seconds
    ts_res = struct.pack("<I", SAMPLE_RATE)  # 30 000 ticks per sec; one tick per sample when Period=1
    time_origin = struct.pack("<8H", 0, 0, 0, 0, 0, 0, 0, 0)
    chan_count = struct.pack("<I", n_channels)
    basic_wo_size = (
        file_id
        + file_spec
        + b"\x00\x00\x00\x00"  # BytesInHeader placeholder
        + label
        + comment
        + period
        + ts_res
        + time_origin
        + chan_count
    )
    # basic header should be 314 bytes for file spec 2.2 (before BytesInHeader patch)
    if len(basic_wo_size) != 314:
        raise ValueError(f"Unexpected basic header length: {len(basic_wo_size)}")
    return basic_wo_size


def build_extended_headers(n_channels: int) -> bytes:
    """Return concatenated extended headers (66 bytes each)."""
    headers = []
    for ch in range(1, n_channels + 1):
        ext = struct.pack(
            "<2sH16sBBhhhh16sIIHIIH",
            b"CC",  # Type (custom code)
            ch,  # ElectrodeID
            f"chan{ch:03d}".encode().ljust(16, b"\x00"),
            0,  # PhysicalConnector
            0,  # ConnectorPin
            -32768,  # MinDigitalValue
            32767,  # MaxDigitalValue
            int(-32768 * UV_PER_BIT),  # MinAnalogValue (µV)
            int(32767 * UV_PER_BIT),  # MaxAnalogValue
            b"uV".ljust(16, b"\x00"),  # Units
            0,  # HighFreqCorner
            0,  # HighFreqOrder
            0,  # HighFreqType
            0,  # LowFreqCorner
            0,  # LowFreqOrder
            0,  # LowFreqType
        )
        # ext is currently 62 bytes; pad to 66
        ext += b"\x00" * (66 - len(ext))
        headers.append(ext)
    return b"".join(headers)


def write_ns5(file_path: Path, data_gen, n_channels: int):
    """Write NS5 file given a generator yielding int16 arrays shaped (samples, channels)."""
    basic_header = build_basic_header(n_channels)
    ext_headers = build_extended_headers(n_channels)
    bytes_in_header = len(basic_header) + len(ext_headers)
    # overwrite BytesInHeader (little-endian uint32) at offset 10 (8 bytes FileID + 2 bytes spec)
    basic_header = (
        basic_header[:10] + struct.pack("<I", bytes_in_header) + basic_header[14:]
    )

    with open(file_path, "wb") as f:
        f.write(basic_header)
        f.write(ext_headers)

        samp_counter = 0
        for chunk in data_gen:
            n_pts = chunk.shape[0]
            # packet header: 0x01, timestamp, num_pts
            f.write(b"\x01")
            f.write(struct.pack("<I", samp_counter))
            f.write(struct.pack("<I", n_pts))
            # interleave samples
            chunk.tofile(f)
            samp_counter += n_pts


#######################################
#  Broadband synthesis per data chunk #
#######################################

def generate_broadband(
    tc_chunk: np.ndarray,
    sbp_chunk: np.ndarray,
    spike_template: np.ndarray,
    mu: np.ndarray,
    sigma: np.ndarray,
    noise_std_uv: float,
    alpha: float,
    rng: np.random.Generator,
    base_neg_peak_uv: float = DEFAULT_NEG_PEAK_UV,
) -> np.ndarray:
    """Return float broadband array (samples × channels, µV)."""
    n_bins, n_ch = tc_chunk.shape
    samples = n_bins * BIN_SAMPLES
    out = rng.normal(0.0, noise_std_uv, size=(samples, n_ch)).astype(np.float32)
    tmpl_len = len(spike_template)

    for ch in range(n_ch):
        for b in range(n_bins):
            k = tc_chunk[b, ch]
            if k == 0:
                continue
            sbp_val = sbp_chunk[b, ch]
            scale = 1.0 + alpha * (sbp_val - mu[ch]) / sigma[ch]
            scale = np.clip(scale, 0.2, 3.0)
            amp = base_neg_peak_uv * scale
            wav = spike_template * amp
            for _ in range(k):
                offset = rng.integers(0, BIN_SAMPLES - tmpl_len)
                idx0 = b * BIN_SAMPLES + offset
                out[idx0 : idx0 + tmpl_len, ch] += wav
    return out


########################
#  Main CLI entrypoint #
########################

def main():
    parser = argparse.ArgumentParser(description="Convert simulated binned features to a synthetic NS5 file.")
    parser.add_argument("--mat-glob", required=True, help="Glob pattern for input MAT files (e.g. 'data/*/*.mat')")
    parser.add_argument("--out", required=True, help="Output NS5 filename")
    parser.add_argument("--alpha", type=float, default=DEFAULT_ALPHA, help="SBP scaling factor")
    parser.add_argument("--noise-uv", type=float, default=DEFAULT_NOISE_STD_UV, help="Gaussian noise SD in µV")
    parser.add_argument("--neg-peak-uv", type=float, default=DEFAULT_NEG_PEAK_UV, help="Base negative spike amplitude in µV")
    parser.add_argument("--chunk-bins", type=int, default=1000, help="Number of 10 ms bins per synthesis chunk")
    parser.add_argument("--seed", type=int, default=42, help="RNG seed")
    args = parser.parse_args()

    rng = np.random.default_rng(args.seed)

    mat_files = list_mat_files(args.mat_glob)
    print(f"Found {len(mat_files)} MAT files.")

    # probe first file for channel count
    tc0, _ = load_mat_arrays(mat_files[0])
    n_ch = tc0.shape[1]
    print(f"Channel count: {n_ch}")

    # compute SBP stats across all files
    print("Computing SBP mean/std across files…")
    mu_ch, sigma_ch = compute_sbp_stats(mat_files, n_ch)

    spike_template = build_spike_template()

    def data_generator():
        for mf in mat_files:
            print(f"Processing {mf.name}…")
            tc, sp = load_mat_arrays(mf)
            n_bins_total = tc.shape[0]
            for start in range(0, n_bins_total, args.chunk_bins):
                end = min(start + args.chunk_bins, n_bins_total)
                chunk_tc = tc[start:end]
                chunk_sp = sp[start:end]
                bb = generate_broadband(
                    chunk_tc,
                    chunk_sp,
                    spike_template,
                    mu_ch,
                    sigma_ch,
                    args.noise_uv,
                    args.alpha,
                    rng,
                    args.neg_peak_uv,
                )
                # convert to int16 counts
                bb_counts = np.clip(bb / UV_PER_BIT, -32768, 32767).astype(np.int16)
                yield bb_counts

    print(f"Writing NS5 to {args.out}…")
    write_ns5(Path(args.out), data_generator(), n_ch)
    print("Done.")


if __name__ == "__main__":
    main() 